node {
    def mvnHome
    stage('Getting Project') {
        git 'https://github.com/camaucrab/springdemo.git'
        mvnHome = tool 'M3'
    }
    stage('Build Project') {
        bat 'echo hello'
    }
    stage('Push Project To Nexus') {
        bat 'echo hello'
    }
}