node {
    def mvnHome
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git 'https://github.com/camaucrab/springdemo.git'
        branch 'master'
        // Get the Maven tool.
        // ** NOTE: This 'M3' Maven tool must be configured
        // **       in the global configuration.
        mvnHome = tool 'M3'
    }
    stage('BUILD and TEST') {
        // Run the maven build
        withEnv(["MVN_HOME=$mvnHome"]) {
            if (isUnix()) {
//                 sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package -DskipTests'
                sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'
            } else {
                bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore clean package /)
//                 bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore clean package -DskipTests /)
            }
        }
    }
    stage('TEST Result') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archiveArtifacts 'target/*.jar'
        jacoco(
              execPattern: 'target/*.exec',
              classPattern: 'target/classes',
              sourcePattern: 'src/main/java',
              exclusionPattern: 'src/test*'
        )
        cucumber buildStatus: 'STABLE',
                            reportTitle: 'Testing Report',
                            fileIncludePattern: '**/cucumber.json',x
                            trendsLimit: 10,
                            classifications: [
                                [
                                    'key': 'Browser',
                                    'value': 'Firefox'
                                ]
                            ]
    }
//     stage('Run Unit Test ') {
//         // Run the maven build
//         withEnv(["MVN_HOME=$mvnHome"]) {
//             if (isUnix()) {
//                 sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore  test -Dtest="com.pdtdang.demospringboot.**.**.**"'
//             } else {
//                 bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore test -Dtest="com.pdtdang.demospringboot.**.**.**"/)
//             }
//         }
//         buildStatus: 'STABLE'
//     }
//     stage('Run SIT Testing ') {
//         // Run the maven build
//         withEnv(["MVN_HOME=$mvnHome"]) {
//             if (isUnix()) {
//                 sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore test -Dtest="SIT.customer.**'
//             } else {
//                 bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore test -Dtest="SIT.customer.**/)
//             }
//         }
//         buildStatus: 'STABLE'
//     }
//
//     stage('SIT Testing report') {
//             cucumber buildStatus: 'STABLE',
//                     reportTitle: 'Testing Report',
//                     fileIncludePattern: '**/cucumber.json',
//                     trendsLimit: 10,
//                     classifications: [
//                         [
//                             'key': 'Browser',
//                             'value': 'Firefox'
//                         ]
//                     ]
//     }
//     stage('Test Coverage Report') {
//             jacoco(
//                   execPattern: 'target/*.exec',
//                   classPattern: 'target/classes',
//                   sourcePattern: 'src/main/java',
//                   exclusionPattern: 'src/test*'
//             )
//     }
}
